import french_toast_img from "../img/breakfast/frenchtoast.jpg";
import omelette_img from "../img/breakfast/omelette.jpg";
import pancake_img from "../img/breakfast/pancake.jpg";
import kor_chicken_img from "../img/dinner/korean_fried_chicken.jpg";
import lasagna_img from "../img/dinner/lasagna.jpg";
import spagetti_img from "../img/dinner/spagetti_bolognese.jpg";
import pizza_img from "../img/lunch/pizza.jpg";
import hot_dog_img from "../img/lunch/hotdog.jpg";
import burger_img from "../img/lunch/burger.jpg";
import fruit_snack_img from "../img/snacks/fruit_snack.jpg";
import granola_img from "../img/snacks/granola.jpg";
import pinwheel_pizza_img from "../img/snacks/pinwheel_pizza.jpg";

export const MOCK_DATA = [
  {
    id: 1,
    recipe_title: "French Toast",
    recipe_upload_date: new Date(2019, 11, 17),
    recipe_summary: "My French Toast recipe, very delicious and enjoyable",
    recipe_img: french_toast_img,
    prep_time_number: 1,
    prep_time_unit: "hours",
    cook_time_number: 1,
    cook_time_unit: "hours",
    num_servings: 2,
    food_type: "Breakfast",
    ingredients: [
      { name: "Eggs", amount: 5, unit: "N/A" },
      { name: "Bread", amount: 6, unit: "N/A" },
    ],
    instructions: ["Crack eggs", "Drench bread in eggs", "Serve"],
  },
  {
    id: 2,
    recipe_title: "Omelette",
    recipe_upload_date: new Date(2018, 11, 17),
    recipe_summary: "My Omelette recipe, very delicious and enjoyable",
    recipe_img: omelette_img,
    prep_time_number: 1,
    prep_time_unit: "hours",
    cook_time_number: 1,
    cook_time_unit: "hours",
    num_servings: 2,
    food_type: "Breakfast",
    ingredients: [{ name: "Eggs", amount: 5, unit: "N/A" }],
    instructions: ["Crack eggs", "Make omelette", "Serve"],
  },
  {
    id: 3,
    recipe_title: "Pancake",
    recipe_upload_date: new Date(2017, 11, 17),
    recipe_summary: "My Pancake recipe, very delicious and enjoyable",
    recipe_img: pancake_img,
    prep_time_number: 1,
    prep_time_unit: "hours",
    cook_time_number: 1,
    cook_time_unit: "hours",
    num_servings: 2,
    food_type: "Breakfast",
    ingredients: [{ name: "Pancake batter", amount: 5, unit: "gram" }],
    instructions: ["Make pancakes", "Serve"],
  },
  {
    id: 4,
    recipe_title: "Korean Fried Chicken",
    recipe_upload_date: new Date(2016, 11, 17),
    recipe_summary:
      "My Korean Fried Chicken recipe, very delicious and enjoyable",
    recipe_img: kor_chicken_img,
    prep_time_number: 1,
    prep_time_unit: "hours",
    cook_time_number: 1,
    cook_time_unit: "hours",
    num_servings: 2,
    food_type: "Dinner",
    ingredients: [
      { name: "Chicken", amount: 5, unit: "kilogram" },
      { name: "Korean sauce", amount: 6, unit: "gram" },
    ],
    instructions: ["Cook chicken", "Drench chicken in sauce", "Serve"],
  },
  {
    id: 5,
    recipe_title: "Lasagna",
    recipe_upload_date: new Date(2015, 11, 17),
    recipe_summary: "My Lasagna recipe, very delicious and enjoyable",
    recipe_img: lasagna_img,
    prep_time_number: 1,
    prep_time_unit: "hours",
    cook_time_number: 1,
    cook_time_unit: "hours",
    num_servings: 2,
    food_type: "Dinner",
    ingredients: [
      { name: "Lasagna noodles", amount: 12, unit: "N/A" },
      { name: "Tomato sauce", amount: 20, unit: "gram" },
    ],
    instructions: ["Cook lasagna", "Serve"],
  },
  {
    id: 6,
    recipe_title: "Spagetti Bolognese",
    recipe_upload_date: new Date(2014, 11, 17),
    recipe_summary:
      "My Spagetti Bolognese recipe, very delicious and enjoyable",
    recipe_img: spagetti_img,
    prep_time_number: 1,
    prep_time_unit: "hours",
    cook_time_number: 1,
    cook_time_unit: "hours",
    num_servings: 2,
    food_type: "Dinner",
    ingredients: [
      { name: "Noodles", amount: 50, unit: "gram" },
      { name: "Tomato sauce", amount: 20, unit: "gram" },
    ],
    instructions: ["Cook pasta", "Add sauce", "Serve"],
  },
  {
    id: 7,
    recipe_title: "Burger",
    recipe_upload_date: new Date(2020, 11, 17),
    recipe_summary: "My Burger recipe, very delicious and enjoyable",
    recipe_img: burger_img,
    prep_time_number: 1,
    prep_time_unit: "hours",
    cook_time_number: 1,
    cook_time_unit: "hours",
    num_servings: 2,
    food_type: "Lunch",
    ingredients: [
      { name: "Burger patties", amount: 6, unit: "N/A" },
      { name: "Buns", amount: 12, unit: "N/A" },
    ],
    instructions: ["Cook patties", "Add buns", "Serve"],
  },
  {
    id: 8,
    recipe_title: "Hot dog",
    recipe_upload_date: new Date(2021, 11, 17),
    recipe_summary: "My Hot dog recipe, very delicious and enjoyable",
    recipe_img: hot_dog_img,
    prep_time_number: 1,
    prep_time_unit: "hours",
    cook_time_number: 1,
    cook_time_unit: "hours",
    num_servings: 2,
    food_type: "Lunch",
    ingredients: [
      { name: "Sausages", amount: 5, unit: "N/A" },
      { name: "Hot dog buns", amount: 5, unit: "N/A" },
    ],
    instructions: ["Cook sausages", "Add bungs", "Serve"],
  },
  {
    id: 9,
    recipe_title: "Pizza",
    recipe_upload_date: new Date(2022, 11, 17),
    recipe_summary: "My Pizza recipe, very delicious and enjoyable",
    recipe_img: pizza_img,
    prep_time_number: 1,
    prep_time_unit: "hours",
    cook_time_number: 1,
    cook_time_unit: "hours",
    num_servings: 2,
    food_type: "Lunch",
    ingredients: [
      { name: "Pizza dough", amount: 20, unit: "gram" },
      { name: "Tomato sauce", amount: 20, unit: "gram" },
      { name: "Mozarella cheese", amount: 20, unit: "gram" },
    ],
    instructions: ["Cook pizza", "Serve"],
  },
  {
    id: 10,
    recipe_title: "Fruit Snack",
    recipe_upload_date: new Date(2020, 11, 17),
    recipe_summary: "My Fruit Snack recipe, very delicious and enjoyable",
    recipe_img: fruit_snack_img,
    prep_time_number: 1,
    prep_time_unit: "hours",
    cook_time_number: 1,
    cook_time_unit: "hours",
    num_servings: 2,
    food_type: "Snack",
    ingredients: [{ name: "gelatin", amount: 5, unit: "gram" }],
    instructions: ["Make fruit snack", "Serve"],
  },
  {
    id: 11,
    recipe_title: "Homemade Granola",
    recipe_upload_date: new Date(2021, 11, 17),
    recipe_summary: "My Homemade Granola recipe, very delicious and enjoyable",
    recipe_img: granola_img,
    prep_time_number: 1,
    prep_time_unit: "hours",
    cook_time_number: 1,
    cook_time_unit: "hours",
    num_servings: 2,
    food_type: "Snack",
    ingredients: [
      { name: "Dried fruit", amount: 5, unit: "gram" },
      { name: "Oats", amount: 6, unit: "gram" },
    ],
    instructions: ["Make granola", "Serve"],
  },
  {
    id: 12,
    recipe_title: "Pinwheel Pizza",
    recipe_upload_date: new Date(2022, 11, 17),
    recipe_summary: "My Pinwheel Pizza recipe, very delicious and enjoyable",
    recipe_img: pinwheel_pizza_img,
    prep_time_number: 1,
    prep_time_unit: "hours",
    cook_time_number: 1,
    cook_time_unit: "hours",
    num_servings: 2,
    food_type: "Snack",
    ingredients: [
      { name: "Pizza dough", amount: 20, unit: "gram" },
      { name: "Tomato sauce", amount: 20, unit: "gram" },
      { name: "Mozarella cheese", amount: 20, unit: "gram" },
    ],
    instructions: ["Cook pizza", "Serve"],
  },
];
